import os
import re

TEMPLATE_DIR = 'src/templates'
OUTPUT_FILE = 'src/generated/templates.h'

def escape_for_cpp(content):
    # Escape backslashes and double quotes
    return content.replace('\\', '\\\\').replace('"', '\\"')

def build():
    if not os.path.exists('src/generated'):
        os.makedirs('src/generated')

    with open(OUTPUT_FILE, 'w') as f:
        f.write('// Auto-generated by build_templates.py\n#include <Arduino.h>\n\n')

        for filename in os.listdir(TEMPLATE_DIR):
            if filename.endswith('.html'):
                name = filename.split('.')[0].upper()
                with open(os.path.join(TEMPLATE_DIR, filename), 'r') as tf:
                    content = tf.read()
                    escaped = escape_for_cpp(content)
                    f.write(f'const char TEMPLATE_{name}[] PROGMEM = R"rawliteral({escaped})rawliteral";\n\n')

if __name__ == '__main__':
    build()
