import os
import re

# Determine project root based on script location or current working dir if executed by SCons
if '__file__' in globals():
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
    PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
else:
    # Fallback for PlatformIO/SCons execution which sets current dir to project root
    PROJECT_DIR = os.getcwd()
    SCRIPT_DIR = os.path.join(PROJECT_DIR, 'scripts')

TEMPLATE_DIR = os.path.join(PROJECT_DIR, 'src', 'templates')
OUTPUT_DIR = os.path.join(PROJECT_DIR, 'src', 'generated')
OUTPUT_H = os.path.join(OUTPUT_DIR, 'templates.h')
CONFIG_FILE = os.path.join(PROJECT_DIR, 'src', 'config.h')
CSS_FILE = os.path.join(TEMPLATE_DIR, 'tailwind.min.css')

def get_mqtt_enabled():
    try:
        with open(CONFIG_FILE, 'r') as f:
            content = f.read()
            return '#define MQTT_SETTINGS_UI_ENABLED 1' in content
    except FileNotFoundError:
        return True # Default to true for simulator

def process_template(content, mqtt_enabled):
    # Replace CDN link with local stylesheet reference
    content = content.replace('<script src="https://cdn.tailwindcss.com"></script>', '<link rel="stylesheet" href="/style.css">')

    # Process conditional blocks for MQTT
    if not mqtt_enabled:
        pattern = re.compile(r'^\s*#if MQTT_SETTINGS_UI_ENABLED.*?(?:#endif|#else)', re.DOTALL | re.MULTILINE)
        content = pattern.sub('', content)
    else:
        # Remove the directives but keep the content
        content = re.sub(r'^\s*#if MQTT_SETTINGS_UI_ENABLED', '', content, flags=re.MULTILINE)
        content = re.sub(r'^\s*#endif', '', content, flags=re.MULTILINE)
    return content

def generate_c_array(file_path, array_name):
    if not os.path.exists(file_path):
        return f"const uint8_t {array_name}[] PROGMEM = {{}};\nconst size_t {array_name}_LEN = 0;\n"

    with open(file_path, 'rb') as f:
        data = f.read()

    # Format exactly 16 bytes per line
    hex_data = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_data.append('  ' + ', '.join([f'0x{b:02x}' for b in chunk]))

    formatted_array = ',\n'.join(hex_data)

    return f"const uint8_t {array_name}[] PROGMEM = {{\n{formatted_array}\n}};\nconst size_t {array_name}_LEN = {len(data)};\n"

def build():
    # Build tailwind css if cli is present
    tailwind_cli = os.path.join(SCRIPT_DIR, 'tailwindcss-linux-x64')
    if os.path.exists(tailwind_cli):
        print("Building Tailwind CSS...")
        os.system(f"{tailwind_cli} -i {os.path.join(TEMPLATE_DIR, 'input.css')} -o {CSS_FILE} --minify")

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    mqtt_enabled = get_mqtt_enabled()

    with open(OUTPUT_H, 'w') as h_file:
        h_file.write('// Auto-generated by build_templates.py\n#ifndef TEMPLATES_H\n#define TEMPLATES_H\n\n#include <Arduino.h>\n\n')

        # Generate CSS constant as string literal
        if os.path.exists(CSS_FILE):
            with open(CSS_FILE, 'r') as f:
                css_content = f.read()
            h_file.write(f'const char TEMPLATE_CSS[] PROGMEM = R"rawliteral({css_content})rawliteral";\n')
            h_file.write(f'const size_t TEMPLATE_CSS_LEN = {len(css_content.encode("utf-8"))};\n\n')
        else:
            h_file.write('const char TEMPLATE_CSS[] PROGMEM = "";\n')
            h_file.write('const size_t TEMPLATE_CSS_LEN = 0;\n\n')

        # Generate HTML constants
        for filename in sorted(os.listdir(TEMPLATE_DIR)):
            if filename.endswith('.html'):
                name = filename.split('.')[0].upper()
                with open(os.path.join(TEMPLATE_DIR, filename), 'r') as tf:
                    content = tf.read()
                    processed_content = process_template(content, mqtt_enabled)

                    h_file.write(f'const char TEMPLATE_{name}[] PROGMEM = R"rawliteral({processed_content})rawliteral";\n\n')

        h_file.write('\n#endif // TEMPLATES_H\n')

    # Remove the .cpp file if it exists (no longer needed)
    cpp_file = os.path.join(OUTPUT_DIR, 'templates.cpp')
    if os.path.exists(cpp_file):
        os.remove(cpp_file)

if __name__ == '__main__':
    build()
