import os

TEMPLATE_DIR = 'src/templates'
OUTPUT_FILE = 'src/generated/templates.h'

def build():
    if not os.path.exists('src/generated'):
        os.makedirs('src/generated')

    with open(OUTPUT_FILE, 'w') as f:
        f.write('// Auto-generated by build_templates.py\n#include <Arduino.h>\n\n')

        # Sort files to ensure stable order
        for filename in sorted(os.listdir(TEMPLATE_DIR)):
            if filename.endswith('.html'):
                name = filename.split('.')[0].upper()
                with open(os.path.join(TEMPLATE_DIR, filename), 'r') as tf:
                    content = tf.read()
                    # R"rawliteral(...)rawliteral" handles quotes automatically
                    f.write(f'const char TEMPLATE_{name}[] PROGMEM = R"rawliteral({content})rawliteral";\n\n')

if __name__ == '__main__':
    build()
