#ifndef CONFIG_H
#define CONFIG_H

// Include variant-specific configuration (generated by build_variant.py)
// This allows different firmware variants with custom branding and settings
#include "variant_config.h"

// Feature flags — native Espressif (PlatformIO) build is the main firmware
// These can be overridden by variant_config.h
#ifndef ENABLE_P1_READER
  #define ENABLE_P1_READER 1  // DSMR P1 reader enabled
#endif

#ifndef ENABLE_MQTT
  #define ENABLE_MQTT 1       // MQTT client enabled
#endif

#ifndef ENABLE_OTA
  #define ENABLE_OTA 1        // OTA updates enabled
#endif

// Firmware version (bump on release: minor = features, patch = fixes)
// FW_EXT is defined in variant_config.h (e.g., "ow", "acme", etc.)
#define FIRMWARE_VERSION_BASE "v1.0.25"
#define FIRMWARE_VERSION FIRMWARE_VERSION_BASE "-" FW_EXT

// Device naming - SSID_PREFIX defined in variant_config.h
// Results in: <SSID_PREFIX>-P1<XXXXXX> (e.g., "OpenWatt-P184B518")
#define DEVICE_NAME_PREFIX SSID_PREFIX "-P1"

// Default AP SSID prefix (legacy - use SSID_PREFIX from variant instead)
#define AP_SSID_PREFIX SSID_PREFIX

// Security salt for password generation
#define SALT_STRING "CHANGE_ME_SALT"

// MQTT Configuration
// If ALLOW_MQTT_CHANGES is 0, these are locked values
#ifndef MQTT_BROKER_HOST
  #define MQTT_BROKER_HOST "mqtt.example.com"
#endif

#ifndef MQTT_BROKER_PORT
  #define MQTT_BROKER_PORT 8883  // TLS port
#endif

#define MQTT_BROKER_PORT_PLAIN 1883  // Plain port (for testing)
#define MQTT_DEFAULT_TOPIC "P1M5/"

// MQTT Publish interval (milliseconds) - default 5 seconds
#define MQTT_PUBLISH_INTERVAL_MS 5000

// MQTT Status publish interval (milliseconds) - default 60 seconds for firmware info
#define MQTT_STATUS_INTERVAL_MS 60000

// UI Configuration
// UI_THEME defined in variant_config.h ("default", "custom", etc.)

#endif
