// Default variant configuration (fallback)
// This file is auto-generated by scripts/build_variant.py
// If building without the script, these defaults will be used

#ifndef VARIANT_CONFIG_H
#define VARIANT_CONFIG_H

// Default values (standard OpenWatt firmware)
#ifndef FW_EXT
  #define FW_EXT "ow"
#endif

#ifndef SSID_PREFIX
  #define SSID_PREFIX "OpenWatt"
#endif

#ifndef ALLOW_MQTT_CHANGES
  #define ALLOW_MQTT_CHANGES 1
#endif

#ifndef ENABLE_MQTT
  #define ENABLE_MQTT 1
#endif

#ifndef ENABLE_OTA
  #define ENABLE_OTA 1
#endif

#ifndef ENABLE_P1_READER
  #define ENABLE_P1_READER 1
#endif

#ifndef UI_THEME
  #define UI_THEME "default"
#endif

#endif // VARIANT_CONFIG_H
