#include "web_ui.h"

String getWebPage(const String& path) {
  String logo = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 40\" class=\"h-8 w-auto\"><path fill=\"currentColor\" d=\"M20 8c-6.6 0-12 5.4-12 12s5.4 12 12 12 12-5.4 12-12S26.6 8 20 8zm0 20c-4.4 0-8-3.6-8-8s3.6-8 8-8 8 3.6 8 8-3.6 8-8 8z\"/><circle cx=\"20\" cy=\"20\" r=\"4\" fill=\"currentColor\"/></svg>";
  
  if (path == "/" || path == "/index.html") {
    String html = "<!DOCTYPE html><html lang=en class=scroll-smooth><head>";
    html += "<meta charset=UTF-8><meta name=viewport content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no\">";
    html += "<title>OpenWatt P1 Reader</title>";
    html += "<script src=https://cdn.tailwindcss.com></script>";
    html += "<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=stylesheet>";
    html += "<style>body{font-family:Inter,system-ui,sans-serif}</style>";
    html += "<script>tailwind.config={theme:{extend:{colors:{primary:{50:'#eff6ff',100:'#dbeafe',500:'#3b82f6',600:'#2563eb',700:'#1d4ed8'}}}}}</script>";
    html += "</head><body class=bg-gray-50 text-gray-900 min-h-screen>";
    html += "<nav class=\"bg-white border-b border-gray-200 sticky top-0 z-50\">";
    html += "<div class=\"max-w-7xl mx-auto px-4\"><div class=\"flex justify-between h-16\">";
    html += "<div class=\"flex items-center gap-3\"><div class=text-blue-600>" + logo + "</div><span class=\"font-semibold text-lg hidden sm:block\">OpenWatt</span></div>";
    html += "<div class=\"flex items-center gap-1\">";
    html += "<a href=/ class=\"px-3 py-2 rounded-lg text-sm font-medium bg-blue-50 text-blue-700\">Dashboard</a>";
    html += "<a href=/live class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">Live</a>";
    html += "<a href=/settings class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">Settings</a>";
    html += "<a href=/system class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">System</a>";
    html += "</div></div></div></nav>";
    html += "<main class=\"max-w-7xl mx-auto px-4 py-6\">";
    html += "<div class=mb-6><h1 class=\"text-2xl font-bold text-gray-900\">Dashboard</h1>";
    html += "<p class=\"mt-1 text-sm text-gray-500\" id=deviceInfo>Loading...</p></div>";
    html += "<div class=\"grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6\">";
    html += "<div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-5\">";
    html += "<div class=\"flex items-center gap-3\"><div class=\"w-10 h-10 rounded-lg bg-emerald-50 flex items-center justify-center\">";
    html += "<svg class=\"w-5 h-5 text-emerald-600\" fill=none stroke=currentColor viewBox=\"0 0 24 24\"><path stroke-linecap=round stroke-linejoin=round stroke-width=2 d=\"M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0\"/></svg>";
    html += "</div><div><p class=\"text-sm font-medium text-gray-600\">WiFi</p>";
    html += "<span id=wifiStatus class=\"inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800\">Disconnected</span>";
    html += "</div></div></div>";
    html += "<div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-5\">";
    html += "<div class=\"flex items-center gap-3\"><div class=\"w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center\">";
    html += "<svg class=\"w-5 h-5 text-blue-600\" fill=none stroke=currentColor viewBox=\"0 0 24 24\"><path stroke-linecap=round stroke-linejoin=round stroke-width=2 d=\"M13 10V3L4 14h7v7l9-11h-7z\"/></svg>";
    html += "</div><div><p class=\"text-sm font-medium text-gray-600\">Meter</p>";
    html += "<span id=meterStatus class=\"inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800\">Disconnected</span>";
    html += "</div></div></div>";
    html += "<div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-5\">";
    html += "<div class=\"flex items-center gap-3\"><div class=\"w-10 h-10 rounded-lg bg-purple-50 flex items-center justify-center\">";
    html += "<svg class=\"w-5 h-5 text-purple-600\" fill=none stroke=currentColor viewBox=\"0 0 24 24\"><path stroke-linecap=round stroke-linejoin=round stroke-width=2 d=\"M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z\"/></svg>";
    html += "</div><div><p class=\"text-sm font-medium text-gray-600\">MQTT</p>";
    html += "<span id=mqttStatus class=\"inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800\">Disconnected</span>";
    html += "</div></div></div></div>";
    html += "<div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-6\">";
    html += "<h2 class=\"text-lg font-semibold text-gray-900 mb-4\">Latest Meter Reading</h2>";
    html += "<div id=latestReading class=\"text-gray-500 text-center py-8\">Waiting for meter data...</div>";
    html += "</div></main>";
    html += "<script>fetch('/api/system').then(r=>r.json()).then(d=>{document.getElementById('deviceInfo').textContent=d.firmware_version+' | '+d.device_id;});";
    html += "function updateStatus(){fetch('/api/state').then(r=>r.json()).then(data=>{const set=(id,ok)=>{const el=document.getElementById(id);el.textContent=ok?'Connected':'Disconnected';el.className='inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium '+(ok?'bg-emerald-100 text-emerald-800':'bg-red-100 text-red-800');};set('wifiStatus',data.wifi_connected);set('meterStatus',data.meter_connected);set('mqttStatus',data.cloud_connected);});}updateStatus();setInterval(updateStatus,5000);</script>";
    html += "</body></html>";
    return html;
  }
  
  if (path == "/live" || path == "/live.html") {
    String html = "<!DOCTYPE html><html lang=en class=scroll-smooth><head>";
    html += "<meta charset=UTF-8><meta name=viewport content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no\">";
    html += "<title>Live Data - OpenWatt</title>";
    html += "<script src=https://cdn.tailwindcss.com></script>";
    html += "<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=stylesheet>";
    html += "<style>body{font-family:Inter,system-ui,sans-serif}</style>";
    html += "</head><body class=bg-gray-50 text-gray-900 min-h-screen>";
    html += "<nav class=\"bg-white border-b border-gray-200 sticky top-0 z-50\">";
    html += "<div class=\"max-w-7xl mx-auto px-4\"><div class=\"flex justify-between h-16\">";
    html += "<div class=\"flex items-center gap-3\"><div class=text-blue-600>" + logo + "</div><span class=\"font-semibold text-lg hidden sm:block\">OpenWatt</span></div>";
    html += "<div class=\"flex items-center gap-1\">";
    html += "<a href=/ class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">Dashboard</a>";
    html += "<a href=/live class=\"px-3 py-2 rounded-lg text-sm font-medium bg-blue-50 text-blue-700\">Live</a>";
    html += "<a href=/settings class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">Settings</a>";
    html += "<a href=/system class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">System</a>";
    html += "</div></div></div></nav>";
    html += "<main class=\"max-w-7xl mx-auto px-4 py-6\">";
    html += "<div class=mb-6><h1 class=\"text-2xl font-bold text-gray-900\">Live Meter Data</h1>";
    html += "<p class=\"mt-1 text-sm text-gray-500\" id=liveVersion>Connecting...</p></div>";
    html += "<div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-4 mb-4\">";
    html += "<div class=\"flex items-center gap-2\">";
    html += "<span id=wsIndicator class=\"w-2.5 h-2.5 rounded-full bg-red-500\"></span>";
    html += "<span id=wsStatus class=\"text-sm font-medium text-gray-600\">Disconnected</span>";
    html += "</div></div>";
    html += "<div class=\"bg-gray-900 rounded-xl shadow-sm overflow-hidden\">";
    html += "<div class=\"p-4 border-b border-gray-800\"><h2 class=\"text-white font-semibold\">Real-time Measurements</h2></div>";
    html += "<div id=meterData class=\"p-4 font-mono text-sm space-y-2\"><div class=text-gray-500>Connecting to WebSocket...</div></div>";
    html += "</div></main>";
    html += "<script>fetch('/api/system').then(r=>r.json()).then(d=>{document.getElementById('liveVersion').textContent='FW '+d.firmware_version;});";
    html += "let ws=null;function connect(){const url=(window.location.protocol==='https:'?'wss:':'ws:')+'//'+window.location.host+'/api/live';ws=new WebSocket(url);";
    html += "ws.onopen=()=>{document.getElementById('wsIndicator').className='w-2.5 h-2.5 rounded-full bg-emerald-500';document.getElementById('wsStatus').textContent='Connected';};";
    html += "ws.onmessage=(e)=>{const data=JSON.parse(e.data);document.getElementById('meterData').innerHTML=";
    html += "'<div class=\"flex justify-between text-gray-400\"><span>Equipment ID</span><span class=text-emerald-400>'+(data['0-0:96.1.1']||'N/A')+'</span></div>'+";
    html += "'<div class=\"flex justify-between text-gray-400\"><span>Timestamp</span><span class=text-blue-400>'+(data['0-0:1.0.0']||'N/A')+'</span></div>'+";
    html += "'<div class=\"flex justify-between text-gray-400\"><span>Power Consumed</span><span class=text-yellow-400>'+(data['1-0:1.7.0']||0)+' kW</span></div>'+";
    html += "'<div class=\"flex justify-between text-gray-400\"><span>Power Produced</span><span class=text-green-400>'+(data['1-0:2.7.0']||0)+' kW</span></div>'+";
    html += "'<div class=\"flex justify-between text-gray-400\"><span>Consumption T1</span><span class=text-purple-400>'+(data['1-0:1.8.1']||0)+' kWh</span></div>'+";
    html += "'<div class=\"flex justify-between text-gray-400\"><span>Consumption T2</span><span class=text-pink-400>'+(data['1-0:1.8.2']||0)+' kWh</span></div>';};";
    html += "ws.onclose=()=>{document.getElementById('wsIndicator').className='w-2.5 h-2.5 rounded-full bg-red-500';document.getElementById('wsStatus').textContent='Disconnected - Reconnecting...';setTimeout(connect,3000);};}connect();</script>";
    html += "</body></html>";
    return html;
  }
  
  if (path == "/settings" || path == "/settings.html") {
    String html = "<!DOCTYPE html><html lang=en class=scroll-smooth><head>";
    html += "<meta charset=UTF-8><meta name=viewport content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no\">";
    html += "<title>Settings - OpenWatt</title>";
    html += "<script src=https://cdn.tailwindcss.com></script>";
    html += "<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=stylesheet>";
    html += "<style>body{font-family:Inter,system-ui,sans-serif}</style>";
    html += "</head><body class=bg-gray-50 text-gray-900 min-h-screen>";
    html += "<nav class=\"bg-white border-b border-gray-200 sticky top-0 z-50\">";
    html += "<div class=\"max-w-7xl mx-auto px-4\"><div class=\"flex justify-between h-16\">";
    html += "<div class=\"flex items-center gap-3\"><div class=text-blue-600>" + logo + "</div><span class=\"font-semibold text-lg hidden sm:block\">OpenWatt</span></div>";
    html += "<div class=\"flex items-center gap-1\">";
    html += "<a href=/ class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">Dashboard</a>";
    html += "<a href=/live class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">Live</a>";
    html += "<a href=/settings class=\"px-3 py-2 rounded-lg text-sm font-medium bg-blue-50 text-blue-700\">Settings</a>";
    html += "<a href=/system class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">System</a>";
    html += "</div></div></div></nav>";
    html += "<main class=\"max-w-3xl mx-auto px-4 py-6\">";
    html += "<div class=mb-6><h1 class=\"text-2xl font-bold text-gray-900\">Settings</h1>";
    html += "<p class=\"mt-1 text-sm text-gray-500\" id=settingsVersion>Loading...</p></div>";
    html += "<div id=message></div>";
    html += "<div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-6\">";
    html += "<h2 class=\"text-lg font-semibold text-gray-900 mb-4\">WiFi Configuration</h2>";
    html += "<form id=wifiForm class=space-y-4>";
    html += "<div><button type=button onclick=scanWiFi() class=\"inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm font-medium\">Scan Networks</button>";
    html += "<div id=wifiList class=\"mt-3 space-y-1\"></div></div>";
    html += "<div><label class=\"block text-sm font-medium text-gray-700 mb-1\">SSID</label>";
    html += "<input type=text id=wifiSSID required class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500\"></div>";
    html += "<div><label class=\"block text-sm font-medium text-gray-700 mb-1\">Password</label>";
    html += "<input type=password id=wifiPassword class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500\"></div>";
    html += "<button type=submit class=\"w-full sm:w-auto px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm font-medium\">Save WiFi Settings</button>";
    html += "</form></div>";
    html += "<div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-6\">";
    html += "<h2 class=\"text-lg font-semibold text-gray-900 mb-4\">MQTT Configuration</h2>";
    html += "<form id=mqttForm class=space-y-4>";
    html += "<div><label class=\"block text-sm font-medium text-gray-700 mb-1\">Broker Host</label>";
    html += "<input type=text id=mqttHost class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500\"></div>";
    html += "<div><label class=\"block text-sm font-medium text-gray-700 mb-1\">Port</label>";
    html += "<input type=number id=mqttPort value=1883 class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500\"></div>";
    html += "<div><label class=\"block text-sm font-medium text-gray-700 mb-1\">Topic</label>";
    html += "<input type=text id=mqttTopic class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500\"></div>";
    html += "<button type=submit class=\"w-full sm:w-auto px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm font-medium\">Save MQTT Settings</button>";
    html += "</form></div></main>";
    html += "<script>fetch('/api/system').then(r=>r.json()).then(d=>{document.getElementById('settingsVersion').textContent='FW '+d.firmware_version;});";
    html += "fetch('/api/config').then(r=>r.json()).then(data=>{if(data.wifi&&data.wifi.ssid)document.getElementById('wifiSSID').value=data.wifi.ssid;if(data.mqtt){document.getElementById('mqttHost').value=data.mqtt.host||'';document.getElementById('mqttPort').value=data.mqtt.port||1883;document.getElementById('mqttTopic').value=data.mqtt.topic||'';}});";
    html += "function scanWiFi(){const list=document.getElementById('wifiList');list.innerHTML='<div class=text-sm text-gray-500>Scanning...</div>';fetch('/api/config/wifiscan').then(r=>r.json()).then(data=>{if(data.error){list.innerHTML='<div class=text-sm text-red-600>'+data.error+'</div>';return;}const nets=data.networks||[];if(nets.length===0){list.innerHTML='<div class=text-sm text-gray-500>No networks found</div>';return;}list.innerHTML=nets.map(n=>'<div class=wifi-row p-2 hover:bg-gray-50 cursor-pointer rounded text-sm data-ssid='+(n.ssid||'')+'><span class=font-medium>'+(n.ssid||'')+'</span><span class=text-gray-400 ml-2>'+(n.rssi||0)+' dBm</span></div>').join('');list.querySelectorAll('.wifi-row').forEach(el=>{el.onclick=()=>{document.getElementById('wifiSSID').value=el.getAttribute('data-ssid')||'';};});}).catch(()=>{list.innerHTML='<div class=text-sm text-red-600>Scan failed</div>';});}";
    html += "document.getElementById('wifiForm').addEventListener('submit',(e)=>{e.preventDefault();fetch('/api/config/wifi',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({wifi:{ssid:document.getElementById('wifiSSID').value,password:document.getElementById('wifiPassword').value}})}).then(()=>{document.getElementById('message').innerHTML='<div class=\"mb-4 p-4 bg-emerald-50 text-emerald-700 rounded-lg\">WiFi saved! Restarting...</div>';setTimeout(()=>window.location.href='/',2000);});});";
    html += "document.getElementById('mqttForm').addEventListener('submit',(e)=>{e.preventDefault();fetch('/api/config/mqtt',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({mqtt:{host:document.getElementById('mqttHost').value,port:parseInt(document.getElementById('mqttPort').value),topic:document.getElementById('mqttTopic').value}})}).then(()=>{document.getElementById('message').innerHTML='<div class=\"mb-4 p-4 bg-emerald-50 text-emerald-700 rounded-lg\">MQTT settings saved!</div>';});});</script>";
    html += "</body></html>";
    return html;
  }
  
  if (path == "/system" || path == "/system.html") {
    String html = "<!DOCTYPE html><html lang=en class=scroll-smooth><head>";
    html += "<meta charset=UTF-8><meta name=viewport content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no\">";
    html += "<title>System - OpenWatt</title>";
    html += "<script src=https://cdn.tailwindcss.com></script>";
    html += "<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=stylesheet>";
    html += "<style>body{font-family:Inter,system-ui,sans-serif}</style>";
    html += "</head><body class=bg-gray-50 text-gray-900 min-h-screen>";
    html += "<nav class=\"bg-white border-b border-gray-200 sticky top-0 z-50\">";
    html += "<div class=\"max-w-7xl mx-auto px-4\"><div class=\"flex justify-between h-16\">";
    html += "<div class=\"flex items-center gap-3\"><div class=text-blue-600>" + logo + "</div><span class=\"font-semibold text-lg hidden sm:block\">OpenWatt</span></div>";
    html += "<div class=\"flex items-center gap-1\">";
    html += "<a href=/ class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">Dashboard</a>";
    html += "<a href=/live class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">Live</a>";
    html += "<a href=/settings class=\"px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50\">Settings</a>";
    html += "<a href=/system class=\"px-3 py-2 rounded-lg text-sm font-medium bg-blue-50 text-blue-700\">System</a>";
    html += "</div></div></div></nav>";
    html += "<main class=\"max-w-3xl mx-auto px-4 py-6\">";
    html += "<div class=mb-6><h1 class=\"text-2xl font-bold text-gray-900\">System</h1>";
    html += "<p class=\"mt-1 text-sm text-gray-500\" id=systemVersion>Loading...</p></div>";
    html += "<div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-6\">";
    html += "<h2 class=\"text-lg font-semibold text-gray-900 mb-4\">System Information</h2>";
    html += "<div id=systemInfo class=space-y-3><div class=\"flex justify-between py-2\"><span class=text-gray-600>Loading...</span></div></div>";
    html += "</div>";
    html += "<div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-6\">";
    html += "<h2 class=\"text-lg font-semibold text-gray-900 mb-4\">System Actions</h2>";
    html += "<div class=\"flex flex-col sm:flex-row gap-3\">";
    html += "<button onclick=reboot() class=\"inline-flex items-center justify-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm font-medium\">Reboot Device</button>";
    html += "<button onclick=factoryReset() class=\"inline-flex items-center justify-center px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 text-sm font-medium\">Factory Reset</button>";
    html += "</div></div></main>";
    html += "<script>fetch('/api/system').then(r=>r.json()).then(data=>{document.getElementById('systemVersion').textContent='FW '+data.firmware_version;document.getElementById('systemInfo').innerHTML='<div class=\"flex justify-between py-2 border-b border-gray-100\"><span class=text-gray-600>Firmware</span><span class=font-medium>'+data.firmware_version+'</span></div><div class=\"flex justify-between py-2 border-b border-gray-100\"><span class=text-gray-600>Device ID</span><span class=font-medium>'+data.device_id+'</span></div><div class=\"flex justify-between py-2 border-b border-gray-100\"><span class=text-gray-600>Serial</span><span class=font-medium>'+data.serial_number+'</span></div><div class=\"flex justify-between py-2\"><span class=text-gray-600>API URL</span><a href='+window.location.origin+'/api/system class=text-blue-600 hover:underline font-medium>'+window.location.origin+'</a></div>';});";
    html += "function reboot(){if(confirm('Reboot device?'))fetch('/api/system/reboot',{method:'PATCH'});}";
    html += "function factoryReset(){if(confirm('WARNING: This will erase all settings!'))fetch('/api/system/factory_reset',{method:'PATCH'});}</script>";
    html += "</body></html>";
    return html;
  }
  
  return "";
}
